# Generated by Django 5.0 on 2023-12-24 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_resevationmodel_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResevationModel',
            new_name='ReservationModel',
        ),
    ]
