# Generated by Django 5.0 on 2023-12-24 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_resevationmodel_reservationmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationmodel',
            old_name='messege',
            new_name='message',
        ),
    ]
